in this first commit basic html and css files and screenshots are upl…
malikali3/My-Portfolio pull request #1
Opened 2022-02-09 10:27 UTC by malikali3

…oaded

2022-02-09 15:44 UTC, gemmen29 requested changes
Hi @malikali3, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- You add a README that contains only the name and description. you can use the Microverse template for README. [Here is the template](https://github.com/microverseinc/readme-template).
- Please change the title and description of the PR(pull request) with a good title and description you can edit the title from the ` Edit ` button next to the PR title and the description from the three dots icon then press `  Edit `.

_Check the comments under the review._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-09 15:44 UTC, gemmen29 commented on index.html
> +</html>
Kindly your design should match any template from the five templates that microverse provide, Please choose one template from the five. You can find the templates in this [link](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)


| Your design |  Example from template1 in Figma design |
| --- | --- |
| ![student](https://user-images.githubusercontent.com/24703171/153233010-6f4cfdf2-aa3f-486d-8bad-4eee203bb938.PNG) | ![template1](https://user-images.githubusercontent.com/24703171/153233198-04c6a7c5-a6a5-49b3-b495-1a92d6b3052b.png) |
| --- | --- |

2022-02-10 10:53 UTC, Deepakdanger requested changes
Hi @malikali3, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-10 10:53 UTC, Deepakdanger commented on index.html
> +        <h1>Malik Ali</h1>
- [ ] Let's add the logo (if the design has one) on the left, and has a link (a tag).

2022-02-10 10:53 UTC, Deepakdanger commented on index.html
> +        <div class="threebar"></div>
- [ ] Instead of using div to create a hamburger. you can use the hamburger icon from [Font Awesome](https://fontawesome.com/). Kindly use the icon & this icon should be inside `nav` tag

2022-02-10 10:53 UTC, Deepakdanger commented on index.html
> +          <div class="purcircle"><img src="imgs/purcircle.png" alt="purple circle"></div>
- [ ] Instead of using div to place image, Please prefer to use `background- image` in style to place its correct position.

2022-02-10 10:53 UTC, Deepakdanger commented on index.html
> +</ul>
- [ ] After header, all this code should be inside the `section` tag.

2022-02-10 10:53 UTC, Deepakdanger commented on index.html
> +         <h2>I'm Malik <br>
- [ ] Lets use `h1` tag here.

2022-02-10 10:53 UTC, Deepakdanger commented on index.html
> +    <li><img src="imgs/vic.png" alt=""></li>
- [ ] The list of icons uses a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag). Please use `a` tag also.

2022-02-10 12:05 UTC, malikali3 commented on index.html
> +          <div class="purcircle"><img src="imgs/purcircle.png" alt="purple circle"></div>
@Deepakdanger i have done all the changes but I am not sure what you are suggesting me in this comment can you give an example of how can i do it.

thanks

2022-02-10 13:37 UTC, Deepakdanger commented on index.html
> +        <h1>Malik Ali</h1>
@malikali3, Here Logo means the name `Malik  Ali`.

2022-02-11 07:14 UTC, elmar8287 commented on index.html
> +        <h1>Malik Ali</h1>
@malikali3 Yeah you can use it

2022-02-11 07:16 UTC, elmar8287 commented on index.html
> +          <div class="purcircle"><img src="imgs/purcircle.png" alt="purple circle"></div>
@malikali3 It means to use the background in CSS file, as `background-image: url("image url");` [reference here](https://www.w3schools.com/cssref/pr_background-image.asp)

2022-02-11 07:59 UTC, CollinsTatang approved these changes
Hi @malikali3 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![image](https://user-images.githubusercontent.com/55596970/153555878-7f00955d-10b6-489a-9c74-7f21c0cba96b.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-11 08:14 UTC, merged